config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  as :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :drops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'drops#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability 

  def initialize( user ) 
    user ||= User.new                          # guest user 

    if user.admin?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    end 
  end 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drop.rb
class Drop < ApplicationRecord
    belongs_to :user
    has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :drops
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_writer :login
  def login
    @login || self.username || self.email
  end
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase } ] ).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        added_atrs = [:username, :email, :password, :password_confirmation, :remember_me ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_atrs
        devise_parameter_sanitizer.permit :account_update, keys: added_atrs
    end
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController
  before_action :set_drop, only: [:show, :edit, :update, :destroy]

  # GET /drops
  # GET /drops.json
  def index
    @drops = Drop.all
  end

  # GET /drops/1
  # GET /drops/1.json
  def show
  end

  # GET /drops/new
  def new
    if current_user != nil
      @drop = current_user.drops.build
    else
      @drop = User.all[1].drops.build
    end
  end

  # GET /drops/1/edit
  def edit
  end

  # POST /drops
  # POST /drops.json
  def create
    if current_user != nil
      @drop = current_user.drops.new(drop_params)
    else
      @drop = User.all[1].drops.new(drop_params)
    end
      respond_to do |format|
      if @drop.save
        format.html { redirect_to @drop, notice: 'Drop was successfully created.' }
        format.json { render :show, status: :created, location: @drop }
      else
        format.html { render :new }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drops/1
  # PATCH/PUT /drops/1.json
  def update
    respond_to do |format|
      if @drop.update(drop_params)
        format.html { redirect_to @drop, notice: 'Drop was successfully updated.' }
        format.json { render :show, status: :ok, location: @drop }
      else
        format.html { render :edit }
        format.json { render json: @drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drops/1
  # DELETE /drops/1.json
  def destroy
    if @drop.file.attached?
      @drop.file.purge
    end
    @drop.destroy
    respond_to do |format|
      format.html { redirect_to drops_url, notice: 'Drop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drop
      @drop = Drop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_params
      params.require(:drop).permit(:title, :description, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/views/drops/_form.html.erb
<%= form_with(model: drop, local: true) do |form| %>
  <% if drop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drop.errors.count, "error") %> prohibited this drop from being saved:</h2>

      <ul>
      <% drop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-md-6 mb-3">
      <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.text_area :description, class:"form-control", placeholder:"Description"  %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.file_field :file, class:"btn btn-light" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.submit class:"btn btn-primary btn-lg btn-block" %>
    </div>
<% end %>

app/views/drops/edit.html.erb
<h1>Editing Drop</h1>

<%= render 'form', drop: @drop %>

<%= link_to 'Show', @drop, class:"btn btn-light" %> |
<%= link_to 'Back', drops_path, class:"btn btn-light" %>

app/views/drops/index.html.erb
<table>
  <tr>
  <% i = 0 %>
  <% @drops.each do |drop| %>
        <% if drop.user == current_user || (current_user != nil && current_user.admin?) %>
        <td><div class="card">
        <div class="card card-header">
        <% if drop.file.attached? %>
          <h6 align="center"><%= drop.file.filename %></h6>
          </div>
          <% if drop.file.content_type[0..4] == "image" %>
            <%= image_tag drop.file, style:"max-height: 64px; width: 64px; margin: auto" %>
          <% else %>
            something
          <% end %>
        <% else %>
        <h6 align="center"><%= drop.title %></h6>
        </div>
        <% end %>
        <%= link_to 'Show', drop, class:"btn btn-info" %>
        <%= link_to 'Edit', edit_drop_path(drop), class:"btn btn-warning" %>
        <%= link_to 'Destroy', drop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        </td>
        </div>  
        <% i += 1 %>
        <% if i == 5 %>
          </tr>
          <tr>
          <% i = 0 %>
        <% end %>
        <% end %>
    <% end %>
</table>

<br>

<%= link_to 'New Drop', new_drop_path, class:"btn btn-primary" %>

app/views/drops/new.html.erb
<div class="col-md-8 order-md-1">
    <h4 class="mb-3">New Drop</h4>

    <%= render 'form', drop: @drop %>
    <div class="col-md-6 mb-3">
        <%= link_to 'Back', drops_path, class:"btn btn-light" %>
    </div>
</div>

app/views/drops/show.html.erb
<% if @drop.user.username == "Guest" || @drop.user == current_user || (current_user != nil && current_user.admin?) %>
<div class="card">
  <div class="card card-header">
  Title
  </div>
  <%= @drop.title %>
</div>
<br>
<div class="card">
  <div class="card card-header">
  Description
  </div>
  <%= @drop.description %>
</div>
<div class="card">
  <div class="card card-header">
  user
  </div>
  <%= @drop.user.username %>
</div>
<br>
<% if @drop.file.attached? %>
<div class="card">
<div class="card card-header">
This is a test
</div>
<br>
<div class="container">
<div class="row">
<div class="col-2">
  <div class="card">
  <div class="card card-header">
  File
  </div>
    <% if @drop.file.content_type[0..4] == "image" %>
    <%= image_tag @drop.file, width:"128px", height:"auto"%>
  <% else %>
    <%= link_to "Download", @drop.file, download: '', class:"btn btn-success" %>
  <% end %>
  <p align="center">.txt</p>
  </div>
</div>
<div class="col">
  <div class="card" style="margin: left;">
  <div class="card card-header">
  Info
  </div>
  Size:52
  name:pa
  upload time:1243124124
  </div>
</div>
</div>
</div>
</div>
<% end %>
<%= link_to 'Edit', edit_drop_path(@drop), class:"btn btn-warning" %> |
<%= link_to 'Destroy', @drop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> |
<%= link_to 'Back', drops_path, class:"btn btn-light" %>
<% else %>
<h3> Sorry, you can't view this page! </h5>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alperenbirol</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>
    <%= stylesheet_link_tag    'signup.css' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to "@Kappastorm", 'https://www.github.com/kappastorm', class:"navbar-brand"%>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", drops_path, class:"nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item active">
            <text class="nav-link">Logged in as <strong><%= current_user.username %></strong></text>
            </li>
            <li class="nav-item active">
            <%= link_to 'Edit profile', edit_user_registration_path, class:'nav-link' %>
            </li>
            <li class="nav-item active">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'nav-link'  %>
            </li>
            <% if current_user.admin?  %>
              <li class="nav-item active">
              <%= link_to "Dashboard", rails_admin_path, class:'nav-link'%>
              </li>
            <% end %>
            <% else %>
              <li class="nav-item active">
              <%= link_to "Sign up", new_user_registration_path, class:'nav-link'  %>
              </li>
              <li class="nav-item active">
              <%= link_to "Login", new_user_session_path, class:'nav-link'  %>
              </li>
          <% end %>
        </ul>
        <%= form_tag drops_path, method: :get, class:"form-inline my-2 my-lg-0" do %>
          <%= text_field_tag :search, params[:search], class:"form-control mr-sm-2", placeholder:"Search" %>
          <%= submit_tag 'Search', :name => nil, class:"btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      </div>
    </nav>
    <div class="container">
    <br>
    <br>
    <br>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>